1. Keluarkan dan tampilkan menggunakan print semua anggota list pada sel dibawah

In [1]:
#kerjakan soal no.1 pada sel berikut ini
#contoh list = [1,2,3]
#contoh hasil
#1
#2
#3
data_list = ['bandung', 'jakarta', 'semarang', 'palembang']
for data in data_list: print(data)

bandung
jakarta
semarang
palembang

2. Keluarkan dan tampilkan menggunakan metode print anggota list dengan tipe numerik (int & float) dari list pada sel di bawah

In [2]:
#kerjakan soal no.2 pada sel berikut ini
#contoh list = ['a', 1]
#contoh hasil :
#1

data_list_2 = [100, 'makassar', 15.5, True, "20"] 
for data in data_list_2:
  if (type(data)==float or type(data)==int): print(data)

100
15.5

3. Buat sebuah kode if else yang dapat menyatakan apakah suatu bilangan ganjil atau genap.

In [3]:
#kerjakan soal no.3 disini

number = 9
print("ganjil" if (number%2==1) else "genap")
 
#hint
# '''
# if ... :
#     print(...)
# else ...:
#     print(...)
# '''
#hasil yang diharapkan
#ganjil

ganjil

4. Kalikan semua anggota list_1 terhadap anggota ganjil pada list_2. tampilkan hasilnya

In [4]:
#kerjakan soal no.4 pada sel berikut ini
list_1 = [1,2,3,4,5]
list_2 = [2,3,6,8,9]

# Generate Odd Element from list_2
oddList2 = [el for el in list_2 if el%2!=0]
# multiply the element
for x in list_1:
  for y in oddList2:
    print(x*y)

#hasil yang diharapkan
# '''
# 3
# 9
# 6
# 18
# 9
# 27
# 12
# 36
# 15
# 45
# '''

3
9
6
18
9
27
12
36
15
45

5. lakukan pengecekan apakah terdapat angka pada tiap2 anggota list. lalu tampilkan sesuai format yang diminta

In [5]:
#kerjakan soal no.5 pada sel berikut ini
#contoh list = ['ada', 'ganesa10']
#contoh hasil:
#ada tidak memiliki angka
#ganesa10 memiliki angka

data_list_3 = ['asda8asd', 'bandunglautanapi', 'washingt0nDC']

for el in data_list_3:
  hasNumber = False
  for char in el:
    if (char.isnumeric()):
      hasNumber = True
      break
  print(f"{el} memiliki angka" if (hasNumber) else f"{el} tidak memiliki angka")

asda8asd memiliki angka
bandunglautanapi tidak memiliki angka
washingt0nDC memiliki angka

6. Cari siswa mana saja yang memiliki nilai lebih dari sama dengan 80. Masukkan kedalam sebuah list. print hasilnya

In [6]:
#kerjakan soal no.6 pada sel berikut ini

data_siswa = [
    {
        "nama":"Budi",
        "nilai": 90
    },
    {
        "nama":"Nina",
        "nilai": 78
    },
    {
        "nama":"Rudi",
        "nilai": 91
    },
    {
        "nama":"Olivia",
        "nilai": 76
    },
    {
        "nama":"Leo",
        "nilai": 80
    },
    {
        "nama":"Liam",
        "nilai": 67
    },
    {
        "nama":"Sheila",
        "nilai": 76
    }
]

#hasil yang diharapkan
#[Budi, Rudi, Leo]

smartStudent = []
for siswa in data_siswa:
  if (siswa.get("nilai")>=80): smartStudent.append(siswa.get("nama"))
print(smartStudent)

['Budi', 'Rudi', 'Leo']